SYMPTOM_RULES = {
    'Apple___Apple_scab': ['brown spots', 'velvety spots', 'twisted leaves', 'olive-green patches'],
    'Apple___Black_rot': ['black spots', 'rotting fruit', 'yellowing leaves', 'cankers on bark'],
    'Apple___Cedar_apple_rust': ['yellow-orange spots', 'rusty patches', 'leaf drop', 'galls on twigs'],
    'Apple___healthy': ['no spots', 'green leaves', 'firm fruit'],
    'Blueberry___healthy': ['no spots', 'green leaves', 'firm berries'],
    'Cherry_(including_sour)___Powdery_mildew': ['white powdery coating', 'curled leaves', 'stunted growth'],
    'Cherry_(including_sour)___healthy': ['no spots', 'green leaves', 'firm cherries'],
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': ['grayish-white spots', 'rectangular lesions', 'leaf wilting'],
    'Corn_(maize)___Common_rust_': ['orange spots', 'rusty patches', 'leaf discoloration'],
    'Corn_(maize)___Northern_Leaf_Blight': ['long gray-green lesions', 'leaf curling', 'wilting'],
    'Corn_(maize)___healthy': ['no spots', 'green leaves', 'strong stalks'],
    'Grape___Black_rot': ['black spots', 'shriveled berries', 'leaf drop', 'brown lesions'],
    'Grape___Esca_(Black_Measles)': ['black streaks', 'tiger stripes on leaves', 'wilting', 'wood discoloration'],
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': ['dark brown spots', 'yellow halos', 'leaf curling'],
    'Grape___healthy': ['no spots', 'green leaves', 'firm grapes'],
    'Orange___Haunglongbing_(Citrus_greening)': ['yellowing leaves', 'bitter fruit', 'uneven ripening', 'leaf drop'],
    'Peach___Bacterial_spot': ['small water-soaked spots', 'black lesions', 'leaf yellowing', 'fruit cracking'],
    'Peach___healthy': ['no spots', 'green leaves', 'firm peaches'],
    'Pepper,_bell___Bacterial_spot': ['dark water-soaked spots', 'yellow halos', 'leaf drop', 'fruit spots'],
    'Pepper,_bell___healthy': ['no spots', 'green leaves', 'firm peppers'],
    'Potato___Early_blight': ['dark brown spots', 'concentric rings', 'yellowing leaves'],
    'Potato___Late_blight': ['dark spots', 'water-soaked lesions', 'white mold', 'rapid wilting'],
    'Potato___healthy': ['no spots', 'green leaves', 'firm tubers'],
    'Raspberry___healthy': ['no spots', 'green leaves', 'firm berries'],
    'Soybean___healthy': ['no spots', 'green leaves', 'healthy pods'],
    'Squash___Powdery_mildew': ['white powdery spots', 'yellowing leaves', 'stunted growth'],
    'Strawberry___Leaf_scorch': ['dark purple spots', 'scorched edges', 'leaf drying'],
    'Strawberry___healthy': ['no spots', 'green leaves', 'firm berries'],
    'Tomato___Bacterial_spot': ['small water-soaked spots', 'black centers', 'yellow halos', 'leaf drop'],
    'Tomato___Early_blight': ['dark brown spots', 'concentric rings', 'yellowing leaves'],
    'Tomato___Late_blight': ['dark spots', 'water-soaked lesions', 'white mold', 'rapid wilting'],
    'Tomato___Leaf_Mold': ['yellow spots', 'grayish-white mold', 'leaf curling'],
    'Tomato___Septoria_leaf_spot': ['small gray spots', 'yellow halos', 'leaf drying'],
    'Tomato___Spider_mites Two-spotted_spider_mite': ['tiny yellow speckles', 'fine webbing', 'leaf bronzing'],
    'Tomato___Target_Spot': ['dark brown spots', 'concentric rings', 'yellow halos'],
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': ['yellow curled leaves', 'stunted growth', 'leaf thickening'],
    'Tomato___Tomato_mosaic_virus': ['mottled leaves', 'yellow streaks', 'stunted growth'],
    'Tomato___healthy': ['no spots', 'green leaves', 'firm tomatoes']
}

# Advice for each disease
DISEASE_ADVICE = {
    'Apple___Apple_scab': 'Apply fungicides like captan or myclobutanil in early spring. Remove and destroy fallen leaves to reduce spore spread.',
    'Apple___Black_rot': 'Prune infected branches, apply fungicides like sulfur, and remove mummified fruit. Improve air circulation around trees.',
    'Apple___Cedar_apple_rust': 'Remove nearby cedar trees if possible. Apply fungicides like triadimefon during wet spring weather.',
    'Apple___healthy': 'Maintain regular watering and fertilization to keep your apple trees healthy.',
    'Blueberry___healthy': 'Continue good cultural practices like proper pruning and mulching to maintain blueberry health.',
    'Cherry_(including_sour)___Powdery_mildew': 'Apply sulfur-based fungicides and improve air circulation by pruning. Avoid overhead watering.',
    'Cherry_(including_sour)___healthy': 'Keep cherries healthy with consistent watering and annual pruning.',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 'Use resistant varieties, apply fungicides like azoxystrobin, and rotate crops to reduce infection.',
    'Corn_(maize)___Common_rust_': 'Plant resistant hybrids and apply fungicides like mancozeb if rust appears early in the season.',
    'Corn_(maize)___Northern_Leaf_Blight': 'Use resistant corn varieties, apply foliar fungicides, and practice crop rotation.',
    'Corn_(maize)___healthy': 'Ensure proper spacing and soil fertility to keep corn thriving.',
    'Grape___Black_rot': 'Apply fungicides like myclobutanil, remove infected berries, and prune for better air flow.',
    'Grape___Esca_(Black_Measles)': 'No cure; remove and destroy affected vines. Avoid wounding vines during pruning.',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 'Apply fungicides like captan and improve canopy ventilation through pruning.',
    'Grape___healthy': 'Maintain vine health with proper irrigation and trellising.',
    'Orange___Haunglongbing_(Citrus_greening)': 'No cure; remove and destroy infected trees. Control psyllid vectors with insecticides.',
    'Peach___Bacterial_spot': 'Use resistant varieties, apply copper-based bactericides, and avoid overhead irrigation.',
    'Peach___healthy': 'Keep peaches healthy with regular pruning and balanced fertilization.',
    'Pepper,_bell___Bacterial_spot': 'Apply copper sprays, remove infected plant parts, and avoid working with wet plants.',
    'Pepper,_bell___healthy': 'Maintain pepper health with well-drained soil and adequate spacing.',
    'Potato___Early_blight': 'Apply fungicides like chlorothalonil, remove infected leaves, and practice crop rotation.',
    'Potato___Late_blight': 'Use resistant varieties, apply fungicides like mancozeb, and destroy infected tubers.',
    'Potato___healthy': 'Keep potatoes healthy with proper hilling and watering practices.',
    'Raspberry___healthy': 'Continue good pruning and mulching to maintain raspberry health.',
    'Soybean___healthy': 'Ensure proper soil drainage and crop rotation to keep soybeans healthy.',
    'Squash___Powdery_mildew': 'Apply fungicides like sulfur, improve air circulation, and avoid overhead watering.',
    'Strawberry___Leaf_scorch': 'Remove and destroy affected leaves, apply fungicides, and improve soil drainage.',
    'Strawberry___healthy': 'Keep strawberries healthy with mulching and regular watering.',
    'Tomato___Bacterial_spot': 'Use copper-based sprays, remove infected parts, and avoid overhead watering.',
    'Tomato___Early_blight': 'Apply fungicides like chlorothalonil, prune lower leaves, and mulch around plants.',
    'Tomato___Late_blight': 'Use resistant varieties, apply fungicides like copper, and destroy infected plants.',
    'Tomato___Leaf_Mold': 'Improve ventilation, apply fungicides like mancozeb, and avoid wetting foliage.',
    'Tomato___Septoria_leaf_spot': 'Remove infected leaves, apply fungicides, and mulch to prevent soil splash.',
    'Tomato___Spider_mites Two-spotted_spider_mite': 'Use miticides or insecticidal soap, increase humidity, and remove heavily infested leaves.',
    'Tomato___Target_Spot': 'Apply fungicides like azoxystrobin, remove infected leaves, and improve air circulation.',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Control whiteflies with insecticides, use resistant varieties, and remove infected plants.',
    'Tomato___Tomato_mosaic_virus': 'Disinfect tools, remove infected plants, and avoid handling plants when wet.',
    'Tomato___healthy': 'Maintain tomato health with staking, watering at the base, and balanced fertilization.'
}